package com.equifax.dibibatch.gcp.varizon_cnx_keying.sql;

import org.apache.beam.sdk.schemas.Schema;
import org.apache.beam.sdk.schemas.Schema.FieldType;

public class CustomSchema {

	public static Schema loadVztDataShareTableForKEYING_FLAG_F() {
		return Schema.builder()
				.addNullableField("DATASHARE_ID", FieldType.STRING)
				.addNullableField("LINE_OF_BUSINESS", FieldType.STRING)
				.addNullableField("BTN", FieldType.STRING)
				.addNullableField("BILL_STREET_NO", FieldType.STRING)
				.addNullableField("BILL_STREET_NAME", FieldType.STRING)
				.addNullableField("BILL_CITY", FieldType.STRING)
				.addNullableField("BILL_STATE", FieldType.STRING)
				.addNullableField("BILL_ZIP", FieldType.STRING)
				.addNullableField("SVC_STREET_NO", FieldType.STRING)
				.addNullableField("SVC_STREET_NAME", FieldType.STRING)
				.addNullableField("SVC_CITY", FieldType.STRING)
				.addNullableField("SVC_STATE", FieldType.STRING)
				.addNullableField("SVC_ZIP", FieldType.STRING)
				.addNullableField("FIRST_NAME", FieldType.STRING)
				.addNullableField("MIDDLE_NAME", FieldType.STRING)
				.addNullableField("LAST_NAME", FieldType.STRING)
				.addNullableField("BUSINESS_NAME", FieldType.STRING)
				.addNullableField("SSN_TAXID", FieldType.STRING)
				.addNullableField("ACCOUNT_NO", FieldType.STRING)
				.addNullableField("LIVE_FINAL_INDICATOR", FieldType.STRING)
				.addNullableField("SOURCE_BUSINESS", FieldType.STRING)
				.addNullableField("FIBER_INDICATOR", FieldType.STRING)
				.addNullableField("KEYING_FLAG", FieldType.STRING)
				.addNullableField("EFX_SVC_CNX_ID", FieldType.STRING)
				.addNullableField("EFX_SVC_HHLD_ID", FieldType.STRING)
				.addNullableField("EFX_SVC_ADDR_ID", FieldType.STRING)
				.addNullableField("EFX_CNX_MODIFY_DT", FieldType.DATETIME)
				.addNullableField("EFX_BEST_KEY_SOURCE", FieldType.STRING)
				.addNullableField("MODIFIED_BY", FieldType.STRING)
				.addNullableField("EFX_CREATE_DT", FieldType.STRING)
				.addNullableField("EFX_CREATE_BATCH_ID", FieldType.INT64)
				.addNullableField("EFX_MODIFY_DT", FieldType.DATETIME)
				.addNullableField("EFX_MODIFY_BATCH_ID", FieldType.INT64)
				.addNullableField("BTN_HMAC", FieldType.STRING)
				.addNullableField("BILL_STREET_NO_HMAC", FieldType.STRING)
				.addNullableField("BILL_STREET_NAME_HMAC", FieldType.STRING)
				.addNullableField("BILL_CITY_HMAC", FieldType.STRING)
				.addNullableField("BILL_STATE_HMAC", FieldType.STRING)
				.addNullableField("BILL_ZIP_HMAC", FieldType.STRING)
				.addNullableField("SVC_STREET_NO_HMAC", FieldType.STRING)
				.addNullableField("SVC_STREET_NAME_HMAC", FieldType.STRING)
				.addNullableField("SVC_CITY_HMAC", FieldType.STRING)
				.addNullableField("SVC_STATE_HMAC", FieldType.STRING)
				.addNullableField("SVC_ZIP_HMAC", FieldType.STRING)
				.addNullableField("FIRST_NAME_HMAC", FieldType.STRING)
				.addNullableField("MIDDLE_NAME_HMAC", FieldType.STRING)
				.addNullableField("LAST_NAME_HMAC", FieldType.STRING)
				.addNullableField("BUSINESS_NAME_HMAC", FieldType.STRING)
				.addNullableField("SSN_TAXID_HMAC", FieldType.STRING)
				.addNullableField("ACCOUNT_NO_HMAC", FieldType.STRING)
				

				.build();
	}

	public static Schema extrDataForVztDataShareTable() {
		return Schema.builder()
				.addNullableField("DATASHARE_ID", FieldType.STRING)
				.addNullableField("LINE_OF_BUSINESS", FieldType.STRING)
				.addNullableField("BTN", FieldType.STRING)
				.addNullableField("BILL_STREET_NO", FieldType.STRING)
				.addNullableField("BILL_STREET_NAME", FieldType.STRING)
				.addNullableField("BILL_CITY", FieldType.STRING)
				.addNullableField("BILL_STATE", FieldType.STRING)
				.addNullableField("BILL_ZIP", FieldType.STRING)
				.addNullableField("SVC_STREET_NO", FieldType.STRING)
				.addNullableField("SVC_STREET_NAME", FieldType.STRING)
				.addNullableField("SVC_CITY", FieldType.STRING)
				.addNullableField("SVC_STATE", FieldType.STRING)
				.addNullableField("SVC_ZIP", FieldType.STRING)
				.addNullableField("FIRST_NAME", FieldType.STRING)
				.addNullableField("MIDDLE_NAME", FieldType.STRING)
				.addNullableField("LAST_NAME", FieldType.STRING)
				.addNullableField("BUSINESS_NAME", FieldType.STRING)
				.addNullableField("SSN_TAXID", FieldType.STRING)
				.addNullableField("ACCOUNT_NO", FieldType.STRING)
				.addNullableField("LIVE_FINAL_INDICATOR", FieldType.STRING)
				.addNullableField("SOURCE_BUSINESS", FieldType.STRING)
				.addNullableField("FIBER_INDICATOR", FieldType.STRING)
				.addNullableField("KEYING_FLAG", FieldType.STRING)
				.addNullableField("EFX_SVC_CNX_ID", FieldType.STRING)
				.addNullableField("EFX_SVC_HHLD_ID", FieldType.STRING)
				.addNullableField("EFX_SVC_ADDR_ID", FieldType.STRING)
				.addNullableField("EFX_CNX_MODIFY_DT", FieldType.STRING)
				.addNullableField("BTN_HMAC", FieldType.STRING)
				.addNullableField("BILL_STREET_NO_HMAC", FieldType.STRING)
				.addNullableField("BILL_STREET_NAME_HMAC", FieldType.STRING)
				.addNullableField("BILL_CITY_HMAC", FieldType.STRING)
				.addNullableField("BILL_STATE_HMAC", FieldType.STRING)
				.addNullableField("BILL_ZIP_HMAC", FieldType.STRING)
				.addNullableField("SVC_STREET_NO_HMAC", FieldType.STRING)
				.addNullableField("SVC_STREET_NAME_HMAC", FieldType.STRING)
				.addNullableField("SVC_CITY_HMAC", FieldType.STRING)
				.addNullableField("SVC_STATE_HMAC", FieldType.STRING)
				.addNullableField("SVC_ZIP_HMAC", FieldType.STRING)
				.addNullableField("FIRST_NAME_HMAC", FieldType.STRING)
				.addNullableField("MIDDLE_NAME_HMAC", FieldType.STRING)
				.addNullableField("LAST_NAME_HMAC", FieldType.STRING)
				.addNullableField("BUSINESS_NAME_HMAC", FieldType.STRING)
				.addNullableField("SSN_TAXID_HMAC", FieldType.STRING)
				.addNullableField("ACCOUNT_NO_HMAC", FieldType.STRING)
				
				.build();
	}

	public static Schema loadVztDataShareTableForKEYING_FLAG_T() {
		
		return Schema.builder()
				.addNullableField("DATASHARE_ID", FieldType.STRING)
				.addNullableField("LINE_OF_BUSINESS", FieldType.STRING)
				.addNullableField("BTN", FieldType.STRING)
				.addNullableField("BILL_STREET_NO", FieldType.STRING)
				.addNullableField("BILL_STREET_NAME", FieldType.STRING)
				.addNullableField("BILL_CITY", FieldType.STRING)
				.addNullableField("BILL_STATE", FieldType.STRING)
				.addNullableField("BILL_ZIP", FieldType.STRING)
				.addNullableField("SVC_STREET_NO", FieldType.STRING)
				.addNullableField("SVC_STREET_NAME", FieldType.STRING)
				.addNullableField("SVC_CITY", FieldType.STRING)
				.addNullableField("SVC_STATE", FieldType.STRING)
				.addNullableField("SVC_ZIP", FieldType.STRING)
				.addNullableField("FIRST_NAME", FieldType.STRING)
				.addNullableField("MIDDLE_NAME", FieldType.STRING)
				.addNullableField("LAST_NAME", FieldType.STRING)
				.addNullableField("BUSINESS_NAME", FieldType.STRING)
				.addNullableField("SSN_TAXID", FieldType.STRING)
				.addNullableField("ACCOUNT_NO", FieldType.STRING)
				.addNullableField("LIVE_FINAL_INDICATOR", FieldType.STRING)
				.addNullableField("SOURCE_BUSINESS", FieldType.STRING)
				.addNullableField("FIBER_INDICATOR", FieldType.STRING)
				.addNullableField("KEYING_FLAG", FieldType.STRING)
				.addNullableField("MODIFIED_BY", FieldType.STRING)
				.addNullableField("EFX_CREATE_DT", FieldType.DATETIME)
				.addNullableField("EFX_CREATE_BATCH_ID", FieldType.INT64)
				.addNullableField("EFX_MODIFY_DT", FieldType.DATETIME)
				.addNullableField("EFX_MODIFY_BATCH_ID", FieldType.INT64)
				.addNullableField("BTN_HMAC", FieldType.STRING)
				.addNullableField("BILL_STREET_NO_HMAC", FieldType.STRING)
				.addNullableField("BILL_STREET_NAME_HMAC", FieldType.STRING)
				.addNullableField("BILL_CITY_HMAC", FieldType.STRING)
				.addNullableField("BILL_STATE_HMAC", FieldType.STRING)
				.addNullableField("BILL_ZIP_HMAC", FieldType.STRING)
				.addNullableField("SVC_STREET_NO_HMAC", FieldType.STRING)
				.addNullableField("SVC_STREET_NAME_HMAC", FieldType.STRING)
				.addNullableField("SVC_CITY_HMAC", FieldType.STRING)
				.addNullableField("SVC_STATE_HMAC", FieldType.STRING)
				.addNullableField("SVC_ZIP_HMAC", FieldType.STRING)
				.addNullableField("FIRST_NAME_HMAC", FieldType.STRING)
				.addNullableField("MIDDLE_NAME_HMAC", FieldType.STRING)
				.addNullableField("LAST_NAME_HMAC", FieldType.STRING)
				.addNullableField("BUSINESS_NAME_HMAC", FieldType.STRING)
				.addNullableField("SSN_TAXID_HMAC", FieldType.STRING)
				.addNullableField("ACCOUNT_NO_HMAC", FieldType.STRING)
				.build();
	}
	}
	


