package com.equifax.dibibatch.gcp.varizon_cnx_keying.sql;

public class ExtractVzDsFuzzyReqExtractSql {

	
	public static final String SELECT_FROM_VW_VZT_DATASHARE = "SELECT A.DATASHARE_ID AS SURROGATE_KEY ,A.FIRST_NAME,A.MIDDLE_NAME,A.LAST_NAME,\r\n" + 
			"A.BILL_STREET_NO,A.BILL_STREET_NAME,A.BILL_CITY,A.BILL_STATE,A.BILL_ZIP,A.SVC_STREET_NO,A.SVC_STREET_NAME,\r\n" + 
			"A.SVC_CITY,A.SVC_STATE,A.SVC_ZIP\r\n" + 
			"FROM {{1}}.VW_VZT_DATASHARE A WHERE\r\n" + 
			"A.FIRST_NAME IS NOT NULL AND\r\n" + 
			"A.LAST_NAME IS NOT NULL AND\r\n" + 
			"A.EFX_CONF_CD IN ('M','L') AND \r\n" + 
			"A.EFX_CNX_MODIFY_BATCH_ID=? AND \r\n" + 
			"A.KEYING_FLAG='T' ORDER BY SURROGATE_KEY";
	public static final String UNION_ALL = "SELECT SURROGATE_KEY, FIRST_NAME,MIDDLE_NAME,LAST_NAME,ADDRESS,CITY,STATE,ZIP\r\n" + 
			"FROM (\r\n" + 
			"SELECT 'B'||A.SURROGATE_KEY AS SURROGATE_KEY,\r\n" + 
			"A.FIRST_NAME,A.MIDDLE_NAME,A.LAST_NAME,\r\n" + 
			"COALESCE(TRIM(A.BILL_STREET_NO ||' '||A.BILL_STREET_NAME),'XXXXXXXXXXX') ADDRESS,\r\n" + 
			"A.BILL_CITY CITY,A.BILL_STATE STATE,A.BILL_ZIP ZIP\r\n" + 
			"FROM  A \r\n" + 
			"UNION ALL \r\n" + 
			"SELECT 'S'|| B.SURROGATE_KEY AS SURROGATE_KEY,\r\n" + 
			"B.FIRST_NAME,B.MIDDLE_NAME,B.LAST_NAME,\r\n" + 
			"TRIM(B.SVC_STREET_NO ||' '||B.SVC_STREET_NAME) ADDRESS,\r\n" + 
			"B.SVC_CITY CITY,B.SVC_STATE STATE,B.SVC_ZIP ZIP\r\n" + 
			"FROM B\r\n" + 
			"WHERE\r\n" + 
			"TRIM(B.SVC_STREET_NO ||' '||B.SVC_STREET_NAME) IS NOT NULL) \r\n"; //+ 

}
