package com.equifax.dibibatch.gcp.varizon_cnx_keying.sql;

public class ExtractFromStDsOutToLoadVztDataShareSql {

	public static final String UPDATE_VZT_DATASHARE_TABLE = "UPDATE {{1}}.VZT_DATASHARE SET EFX_BILL_CNX_ERROR_CODE = ?,EFX_BILL_CNX_ID = ?,EFX_BILL_HHLD_ID = ?,EFX_BILL_ADDR_ID = ?,EFX_BILL_SOURCE_OF_MATCH = ?,EFX_BILL_CONF_CD = ?,EFX_SVC_CNX_ERROR_CODE = ?,EFX_SVC_CNX_ID = ?,EFX_SVC_HHLD_ID = ?,EFX_SVC_ADDR_ID = ?,EFX_SVC_SOURCE_OF_MATCH = ?,EFX_SVC_CONF_CD = ?,EFX_BEST_KEY_SOURCE = ?,MODIFIED_BY = ?,EFX_CNX_MODIFY_DT = ?,EFX_CNX_MODIFY_BATCH_ID = ?,OLD_BEST_CNX_ID = (SELECT EFX_CNX_ID FROM {{1}}.VW_VZT_DATASHARE WHERE DATASHARE_ID = ?) WHERE DATASHARE_ID = ?";
	public static final String SELECT_JOIN_SOURCE_DS_ID = "SELECT SUBSTRING(A.DATASHARE_ID FROM 2 FOR 17) DATASHARE_ID, A.EFX_BILL_CNX_ERROR_CODE , A.EFX_BILL_CNX_ID,  A.EFX_BILL_HHLD_ID,  \r\n" + 
			"CASE A.EFX_BILL_CNX_ERROR_CODE WHEN 'ERADDR' THEN '000000000000'  ELSE A.EFX_BILL_ADDR_ID  END EFX_BILL_ADDR_ID,  \r\n" + 
			"A.EFX_BILL_SOURCE_OF_MATCH, A.EFX_BILL_CONF_CD,B.EFX_SVC_CNX_ERROR_CODE, B.EFX_SVC_CNX_ID, B.EFX_SVC_HHLD_ID,  \r\n" + 
			"CASE B.EFX_SVC_CNX_ERROR_CODE WHEN 'ERADDR' THEN '000000000000' ELSE B.EFX_SVC_ADDR_ID END EFX_SVC_ADDR_ID,  \r\n" + 
			"B.EFX_SVC_SOURCE_OF_MATCH, B.EFX_SVC_CONF_CD,  \r\n" + 
			"CASE WHEN COALESCE( CASE A.EFX_BILL_CONF_CD WHEN 'H' THEN 2 ELSE CASE A.EFX_BILL_CONF_CD WHEN 'M' \r\n" + 
			"THEN 7 ELSE CASE A.EFX_BILL_CONF_CD WHEN 'L' THEN 10 ELSE 999 END END END,999) <= COALESCE(CASE B.EFX_SVC_CONF_CD \r\n" + 
			"WHEN 'H' THEN 2 ELSE CASE B.EFX_SVC_CONF_CD WHEN 'M' THEN 7 ELSE CASE B.EFX_SVC_CONF_CD WHEN 'L' THEN 10 ELSE 999 END END END,999) THEN 'B' ELSE 'S' END EFX_BEST_KEY_SOURCE FROM A RIGHT OUTER JOIN B ON SUBSTRING(A.DATASHARE_ID FROM 2 FOR 17) = SUBSTRING(B.DATASHARE_ID FROM 2 FOR 17) \r\n" + 
			"WHERE  SUBSTRING(A.DATASHARE_ID FROM 1 FOR 1) = 'B' AND SUBSTRING(B.DATASHARE_ID FROM 1 FOR 1) = 'S'" ;			

}
