package com.equifax.dibibatch.gcp.varizon_cnx_keying.sql;

public class LoadVztBatchAndVztSummarySql {

	public static final String SELECT_FROM_VZT_DATASHARE = "SELECT COUNT(*) LOAD_CNT FROM {{1}}.VZT_DATASHARE WHERE EFX_CNX_MODIFY_BATCH_ID = ?";
	public static final String INSERT_VZT_BATCH = "INSERT INTO {{1}}.Vzt_Batch (BATCH_ID, ULTIMATE_BATCH_ID, START_DT, BATCH_NAME, PROCESS_CNT, FAIL_CNT, FILE_NAME, END_DT, REC_CNT, COMMENTS) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String INSERT_VZT_SUMMARY = "INSERT INTO {{1}}.VZT_BATCH_SUMMARY (ULTIMATE_BATCH_ID, CNX_RESPONSE_FILE_BATCH_ID, CNX_RESPONSE_FILE_NAME, CNX_RESPONSE_REC_CNT, CNX_RESPONSE_LOAD_CNT, CNX_RESPONSE_FILE_LOAD_DT) VALUES (?, ?, ?, ?, ?,?)";
	public static final String UPDATE_VZT_SUMMARY = "UPDATE {{1}}.VZT_BATCH_SUMMARY SET CNX_RESPONSE_FILE_BATCH_ID = ?, CNX_RESPONSE_FILE_NAME = ?, CNX_RESPONSE_REC_CNT = ?, CNX_RESPONSE_LOAD_CNT = ?, CNX_RESPONSE_FILE_LOAD_DT = ? WHERE (ULTIMATE_BATCH_ID = ?)";

}
