package com.equifax.dibibatch.gcp.varizon_cnx_keying.sql;

public class LoadVztDataShareCnxRepoFromVwVztDataShareSql {

	
	public static final String SELECT_FROM_VW_VZT_DATASHARE = "SELECT DATASHARE_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, ACCOUNT_NO, EFX_CNX_ID, EFX_HHLD_ID, EFX_ADDR_ID,EFX_SOURCE_OF_MATCH,EFX_BEST_KEY_SOURCE,EFX_CNX_MODIFY_DT,EFX_CONF_CD FROM {{1}}.VW_VZT_DATASHARE WHERE  EFX_ERROR_CODE IS NULL AND EFX_CNX_ID IS NOT NULL AND EFX_CNX_MODIFY_BATCH_ID = ?";
	public static final String INSERT_VZ_DATASHARE_CNX_REPO_TABLE = "INSERT INTO {{1}}.VZ_DATASHARE_CNX_REPO (VZ_DATASHARE_CNX_REPO_ID, DATASHARE_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, ACCOUNT_NO,  EFX_CNX_ID, EFX_HHLD_ID, EFX_ADDR_ID, EFX_SOURCE_OF_MATCH, EFX_BEST_KEY_SOURCE, EFX_CNX_MODIFY_DT, EFX_CONF_CD, EFX_CREATE_DT, EFX_CREATE_BATCH_ID, EFX_MODIFY_DT, EFX_MODIFY_BATCH_ID) \r\n" + 
			"VALUES (nextval('{{1}}.seq_vz_datashare_cnx_repo_ssa'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String UPDATE_VZ_DATASHARE_CNX_REPO_TABLE = "UPDATE {{1}}.VZ_DATASHARE_CNX_REPO SET FIRST_NAME = ?, MIDDLE_NAME = ?, LAST_NAME = ?, ACCOUNT_NO = ?, EFX_CNX_ID = ?, EFX_HHLD_ID = ?, EFX_ADDR_ID = ?, EFX_SOURCE_OF_MATCH = ?, EFX_BEST_KEY_SOURCE = ?, EFX_CNX_MODIFY_DT = ?, EFX_CONF_CD = ?,  EFX_MODIFY_DT = ?, EFX_MODIFY_BATCH_ID = ? WHERE DATASHARE_ID = ?";

}
