package com.equifax.dibibatch.gcp.varizon_cnx_keying.sql;

public class LoadVztBatchSummeryStatsSql {

	public static final String SELECT_FROM_VZT_DATASHARE = "SELECT COUNT(*) LOAD_CNT, ? as INPUT_FILE_DT  FROM {{1}}.VZT_DATASHARE WHERE EFX_MODIFY_BATCH_ID= ?";
	public static final String INSERT_VZT_BATCH = "INSERT INTO {{1}}.VZT_BATCH (BATCH_ID, ULTIMATE_BATCH_ID, START_DT, BATCH_NAME, PROCESS_CNT, FAIL_CNT, FILE_NAME, END_DT, REC_CNT, COMMENTS, LOAD_FAIL_CNT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String INSERT_VZT_BATCH_SUMMARY = "INSERT INTO {{1}}.VZT_BATCH_SUMMARY(ULTIMATE_BATCH_ID, VZT_INPUT_FILE_BATCH_ID, VZT_INPUT_FILE_NAME, VZT_INPUT_FILE_DT, VZT_INPUT_REC_CNT, VZT_INPUT_LOAD_CNT, VZT_INPUT_FAIL_CNT, VZT_KEYING_FLAG_T, VZT_KEYING_FLAG_F, VZT_INPUT_FILE_LOAD_DT, CNX_INPUT_FILE_BATCH_ID, CNX_INPUT_FILE_NAME, CNX_INPUT_FILE_EXTRACT_CNT, CNX_INPUT_FILE_EXTRACT_DT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String INSERT_VZT_BATCH_STATS = "INSERT INTO {{1}}.Vzt_Batch_Stats (ULTIMATE_BATCH_ID, INPUT_FILE_NAME, INPUT_FILE_DT, INPUT_REC_CNT, INPUT_LOAD_CNT, INPUT_FAIL_CNT, INSERT_REC_CNT, UPDATE_REC_CNT, SOURCE_VZT_CNT, SOURCE_VZW_CNT, SOURCE_VZB_CNT, SOURCE_VBB_CNT, LIVE_CNT, FINALS_CNT, HIT_CNT, NOHIT_CNT) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
}
